In [17]:
import gmaps
import pandas as pd

# Google developer API key
from config import gkey

# Configure gmaps
gmaps.configure(api_key=gkey)

In [23]:
# Create earthquake dataframe
tornado_df = pd.read_csv('1950-2017_actual_tornadoes_prelim.csv')
tornado_df.dropna()
tornado_df.head()

,om,yr,mo,dy,date,time,tz,st,stf,stn,...,len,wid,ns,sn,sg,f1,f2,f3,f4,fc
0,1,1950,1,3,1/3/50,11:00:00,3,MO,29,1,...,9.5,150.0,2,0,1,0,0,0,0,0
1,2,1950,1,3,1/3/50,11:55:00,3,IL,17,2,...,3.6,130.0,1,1,1,135,0,0,0,0
2,3,1950,1,3,1/3/50,16:00:00,3,OH,39,1,...,0.1,10.0,1,1,1,161,0,0,0,0
3,4,1950,1,13,1/13/50,5:25:00,3,AR,5,1,...,0.6,17.0,1,1,1,113,0,0,0,0
4,5,1950,1,25,1/25/50,19:30:00,3,MO,29,2,...,2.3,300.0,1,1,1,93,0,0,0,0

In [24]:
# Store latitude and longitude in locations
locations = tornado_df[["slat", "slon"]]

# Fill NaN values and convert to float
rating = tornado_df["mag"].astype(float)

In [26]:
# Plot Heatmap
fig = gmaps.figure()

# Create heat layer
heat_layer = gmaps.heatmap_layer(locations, weights=rating, 
                                 dissipating=False, max_intensity=6,
                                 point_radius=1)


# Add layer
fig.add_layer(heat_layer)

# Display figure
fig

Figure(layout=FigureLayout(height='420px'))